version: '3.5'

services:
  my4ccpd:
    container_name: my4ccpd
    image: mysql:5.7
    restart: always
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci
    ports:
      - 3306:3306
    volumes:
      - "/srv/docker/my4ccpd:/var/lib/mysql"
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - ciscat

  ccpd:
    container_name: ccpd
    build: ./ccpd/
    restart: always
    ports:
      - 80:8080
    volumes:
      - "/srv/docker/ccpd:/data"
    networks:
      - ciscat

  smb:
    container_name: smb
    build: ./smb/
    restart: always
    ports:
      - 445:445
    environment:
      SAMBA_SHARE_NAME: ${SAMBA_SHARE_NAME}
      SAMBA_SERVER_NAME: ${SAMBA_SERVER_NAME}
      CCPD_URL: ${CCPD_URL}
      CCPD_TOKEN: ${CCPD_TOKEN}
      SAMBA_LOG_LEVEL: 3
    volumes:
      - "/srv/docker/smb:/data"
    networks:
      - ciscat

### Default docker subnet IP range is `172.17.0.0/16`
### To avoid conflicts with corporate LAN networking/routing add the following
###   line to `/etc/docker/daemon.json` file: `{"bip": "192.168.168.1/24"}`, using
###   the corresponding subnet from your IP spaces

networks:
  ciscat:
    name: ciscat
    ipam:
      config:
        - subnet: 192.168.169.0/24
          gateway: 192.168.169.1
