version: '3.5'

services:
  my4ccpd:
    container_name: my4ccpd
    image: mysql:5.7
    restart: always
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci
    ports:
      - 3306:3306
    volumes:
      - "/srv/docker/my4ccpd:/var/lib/mysql"
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - cis-ccpd

  ccpd:
    container_name: ccpd
    build: ./
    restart: always
    ports:
      - 80:8080
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_SERVER: my4ccpd
      CCPD_URL: ${CCPD_URL}
      CCPD_TOKEN: ${CCPD_TOKEN}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASS: ${SMTP_PASS}
      DEFAULT_SENDER_EMAIL_ADDRESS: ${DEFAULT_SENDER_EMAIL_ADDRESS}
    volumes:
      - "/srv/docker/ccpd:/data"
    networks:
      - cis-ccpd

### Default docker subnet IP range is `172.17.0.0/16`
### To avoid conflicts with corporate LAN networking/routing add the following
###   line to `/etc/docker/daemon.json` file: `{"bip": "192.168.168.1/24"}`, using
###   the corresponding subnet from your IP spaces

networks:
  cis-ccpd:
    name: cis-ccpd
    ipam:
      config:
        - subnet: 192.168.170.0/24
          gateway: 192.168.170.1
