FROM tomcat:9-jre11

ENV TZ="UTC"

### TODO
### - prepare tomcat
### - extract WAR
### - ...

#COPY entrypoint.sh /entrypoint.sh

#EXPOSE 8080
#VOLUME [ "/data" ]

#ENTRYPOINT [ "/entrypoint.sh" ]
#CMD [ "smbd", "-F", "--no-process-group", "--configfile=/etc/samba/smb.conf" ]

#HEALTHCHECK --interval=30s --timeout=10s CMD smbclient -L \\localhost -U % -m SMB3
